#!/usr/bin/env bash
set -uo pipefail

usage() {
    cat <<'EOF'
Usage:
  run-kwin-virtual.sh [options] -- <command> [args...]

Options:
  --scale VALUE       Run one scale (default: 1).
  --matrix            Run the standard scale matrix: 1, 1.25, 1.5, 2.
  --outputs COUNT     Number of virtual outputs (default: 1).
  --width PIXELS      Virtual output width (default: 1280).
  --height PIXELS     Virtual output height (default: 720).
  --keep-on-failure   Preserve the private environment after a failed run.
  -h, --help          Show this help.
EOF
}

fail() {
    printf 'run-kwin-virtual: %s\n' "$*" >&2
    exit 2
}

require_value() {
    (($# >= 2)) || fail "$1 requires a value"
}

scale="1"
matrix=false
outputs="1"
width="1280"
height="720"
keep_on_failure=false
command_args=()

while (($# > 0)); do
    case "$1" in
    --scale)
        require_value "$@"
        scale="$2"
        shift 2
        ;;
    --matrix)
        matrix=true
        shift
        ;;
    --outputs)
        require_value "$@"
        outputs="$2"
        shift 2
        ;;
    --width)
        require_value "$@"
        width="$2"
        shift 2
        ;;
    --height)
        require_value "$@"
        height="$2"
        shift 2
        ;;
    --keep-on-failure)
        keep_on_failure=true
        shift
        ;;
    -h | --help)
        usage
        exit 0
        ;;
    --)
        shift
        command_args=("$@")
        break
        ;;
    *)
        fail "unknown option: $1"
        ;;
    esac
done

((${#command_args[@]} > 0)) || fail "a command is required after --"
[[ "$outputs" =~ ^[1-9][0-9]*$ ]] || fail "--outputs must be a positive integer"
[[ "$width" =~ ^[1-9][0-9]*$ ]] || fail "--width must be a positive integer"
[[ "$height" =~ ^[1-9][0-9]*$ ]] || fail "--height must be a positive integer"
[[ "$scale" =~ ^([1-9][0-9]*(\.[0-9]+)?|0\.[0-9]*[1-9][0-9]*)$ ]] \
    || fail "--scale must be a positive number"

# KWin's startup output configuration resets virtual outputs to scale 1, so
# non-unit scales must be applied and verified inside the session after KWin
# starts. Scale 1 keeps the original direct launch path.
needs_scale_guard=false
if $matrix || [[ "$scale" != "1" ]]; then
    needs_scale_guard=true
fi

for binary in kwin_wayland dbus-run-session setsid mktemp; do
    command -v "$binary" >/dev/null || fail "required binary is unavailable: $binary"
done
if $needs_scale_guard; then
    for binary in kscreen-doctor python3 timeout; do
        command -v "$binary" >/dev/null || fail "required binary is unavailable: $binary"
    done
fi

kwin_binary="$(command -v kwin_wayland)"
dbus_binary="$(command -v dbus-run-session)"
setsid_binary="$(command -v setsid)"
base="$(mktemp -d "${TMPDIR:-/tmp}/nagi-kwin-virtual.XXXXXX")"
active_pid=""
session_pgid=""

remove_private_state() {
    local attempt
    for attempt in {1..40}; do
        if rm -rf -- "$base" 2>/dev/null && [[ ! -e "$base" ]]; then
            return 0
        fi
        sleep 0.05
    done
    return 1
}

stop_owned_session() {
    # Shut down the owned private session group: polite TERM, a bounded
    # drain, KILL for survivors, and leader reaping. setsid makes the KWin
    # leader the group leader, so the group owns the whole private session,
    # including a launcher or test command orphaned by an early KWin exit.
    # Safe to call after every run and from cleanup; idempotent, and the
    # pgid is forgotten once stopped so matrix runs never leak a group.
    [[ -n "$session_pgid" ]] || return 0
    kill -TERM -- "-$session_pgid" 2>/dev/null || true
    local waited=0
    while kill -0 -- "-$session_pgid" 2>/dev/null && ((waited < 20)); do
        sleep 0.1
        waited=$((waited + 1))
    done
    kill -KILL -- "-$session_pgid" 2>/dev/null || true
    if [[ -n "$active_pid" ]]; then
        wait "$active_pid" 2>/dev/null || true
        active_pid=""
    fi
    session_pgid=""
}

cleanup() {
    local status=$?
    trap - EXIT INT TERM

    stop_owned_session

    if ((status != 0)) && $keep_on_failure; then
        printf 'run-kwin-virtual: preserved failed environment: %s\n' "$base" >&2
    elif ! remove_private_state; then
        printf 'run-kwin-virtual: failed to remove private environment: %s\n' "$base" >&2
        ((status == 0)) && status=1
    fi

    exit "$status"
}

trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

write_scale_guard() {
    local guard_script=$1
    cat >"$guard_script" <<'GUARD'
#!/usr/bin/env bash
# Generated by tests/run-kwin-virtual.sh. Applies the requested scale to the
# outputs of the private virtual KWin session after its startup configuration
# has settled, and verifies count, scale, and left-to-right placement through
# a KScreen readback before the test command runs. Everything here targets
# only the private session inherited from KWin.
set -uo pipefail

(( $# == 3 )) || {
    printf 'run-kwin-virtual: scale guard: bad invocation\n' >&2
    exit 3
}

status_file=$1
expected_outputs=$2
scale=$3

# Per-call and overall bounds for the setup phase, in seconds.
guard_timeout=10
setup_deadline=40

printf '%s\n' running >"$status_file"

guard_exit() {
    printf '%s\n' "$1" >"$status_file"
    exit "$1"
}

guard_fail() {
    printf 'run-kwin-virtual: scale guard: %s\n' "$*" >&2
    guard_exit 3
}

# Discover the session's virtual outputs and emit the kscreen-doctor
# arguments that apply the requested scale and re-pack the outputs with
# KWin's own ceil(pos.x + width/scale) chain, preserving startup order.
plan_config='
import json, math, sys
expected, scale = int(sys.argv[1]), float(sys.argv[2])
try:
    data = json.load(sys.stdin)
except ValueError:
    sys.exit(1)
outs = [
    o for o in data.get("outputs", [])
    if o.get("enabled") and o.get("connected") and str(o.get("name", "")).startswith("Virtual-")
]
if len(outs) != expected:
    print("expected %d virtual outputs, found %d" % (expected, len(outs)))
    sys.exit(1)
outs.sort(key=lambda o: (o.get("pos") or {}).get("x", 0))
next_x = 0.0
for o in outs:
    position = int(math.ceil(next_x - 1e-9))
    print("output.%s.scale.%s" % (o["name"], sys.argv[2]))
    print("output.%s.position.%d,0" % (o["name"], position))
    next_x = position + float(o.get("size", {}).get("width", 0)) / scale
'

# Verify a fresh readback: exact output count, applied scale, and coherent
# left-to-right placement at y=0 with the same ceil accumulation.
verify_config='
import json, math, sys
scale, expected = float(sys.argv[1]), int(sys.argv[2])
try:
    data = json.load(sys.stdin)
except ValueError:
    print("KScreen readback was not valid JSON")
    sys.exit(1)
outs = [
    o for o in data.get("outputs", [])
    if o.get("enabled") and o.get("connected") and str(o.get("name", "")).startswith("Virtual-")
]
if len(outs) != expected:
    print("expected %d virtual outputs, found %d" % (expected, len(outs)))
    sys.exit(1)
for o in outs:
    if abs(float(o.get("scale", 0)) - scale) > 1e-6:
        print("output %s kept scale %s" % (o["name"], o.get("scale")))
        sys.exit(1)
outs.sort(key=lambda o: (o.get("pos") or {}).get("x", 0))
next_x = 0.0
for o in outs:
    pos = o.get("pos") or {}
    x, y = float(pos.get("x", -1)), float(pos.get("y", -1))
    if abs(y) > 1e-6:
        print("output %s sits at y=%g" % (o["name"], y))
        sys.exit(1)
    expected_x = int(math.ceil(next_x - 1e-9))
    if abs(x - expected_x) > 0.5:
        print("output %s sits at x=%g, expected %d" % (o["name"], x, expected_x))
        sys.exit(1)
    next_x = expected_x + float(o.get("size", {}).get("width", 0)) / scale
print("verified scale %s across %d outputs (%s)" % (
    sys.argv[1], expected, ",".join(o["name"] for o in outs)))
'

# Every kscreen-doctor call is bounded so a wedged private session cannot
# hang the runner; discovery additionally obeys the overall wall-clock
# deadline. --foreground keeps the tool in this session's process group so
# the owned-group stop can never miss it.
run_kscreen() {
    timeout --foreground -k 2 "$guard_timeout" kscreen-doctor "$@"
}

attempt=0
while :; do
    if plan="$(run_kscreen -j 2>/dev/null | python3 -c "$plan_config" "$expected_outputs" "$scale")"; then
        break
    fi
    attempt=$((attempt + 1))
    ((attempt <= 200)) || guard_fail "KWin did not expose ${expected_outputs} virtual outputs: ${plan:-no KScreen response}"
    ((SECONDS < setup_deadline)) || guard_fail "KWin setup did not settle within ${setup_deadline}s: ${plan:-no KScreen response}"
    sleep 0.1
done

apply_args=()
while IFS= read -r token; do
    apply_args+=("$token")
done <<<"$plan"

apply_log="$(run_kscreen "${apply_args[@]}")"
apply_status=$?
((apply_status == 0)) || guard_fail "failed to apply scale $scale (status $apply_status): $apply_log"

readback="$(run_kscreen -j)"
readback_status=$?
((readback_status == 0)) || guard_fail "KScreen readback failed (status $readback_status)"
verified="$(printf '%s' "$readback" | python3 -c "$verify_config" "$scale" "$expected_outputs")" \
    || guard_fail "$verified"

printf 'run-kwin-virtual: %s\n' "$verified"
guard_exit 0
GUARD
    chmod 0700 "$guard_script"
}

write_session_launcher() {
    local launcher=$1
    {
        printf '#!/usr/bin/env bash\nset -euo pipefail\n'
        if [[ "$current_scale" != "1" ]]; then
            printf '%q %q %q %q\n' \
                "$root/scale-guard" "$root/guard-status" "$outputs" "$current_scale"
        fi
        printf 'exec'
        printf ' %q' "${command_args[@]}"
        printf '\n'
    } >"$launcher"
    chmod 0700 "$launcher"
}

run_one() {
    local current_scale=$1
    local label=${current_scale//./_}
    local root="$base/scale-$label"
    local runtime="$root/runtime"
    local launcher="$root/session-command"
    local guard_status_file="$root/guard-status"
    local guard_status=""
    local status

    mkdir -p "$root/config" "$root/state" "$root/cache" "$root/data" "$root/home" "$runtime"
    chmod 0700 "$runtime"
    if [[ "${KWIN_TEST_PER_OUTPUT_DESKTOPS:-0}" == "1" ]]; then
        printf '%s\n' '[Windows]' 'PerOutputVirtualDesktops=true' >"$root/config/kwinrc"
    fi
    if [[ "$current_scale" != "1" ]]; then
        write_scale_guard "$root/scale-guard"
    fi
    write_session_launcher "$launcher"

    printf 'run-kwin-virtual: scale=%s outputs=%s geometry=%sx%s root=%s\n' \
        "$current_scale" "$outputs" "$width" "$height" "$root"

    "$setsid_binary" /usr/bin/env \
        -u WAYLAND_DISPLAY \
        -u DISPLAY \
        -u DBUS_SESSION_BUS_ADDRESS \
        -u SSH_AUTH_SOCK \
        HOME="$root/home" \
        XDG_CONFIG_HOME="$root/config" \
        XDG_STATE_HOME="$root/state" \
        XDG_CACHE_HOME="$root/cache" \
        XDG_DATA_HOME="$root/data" \
        XDG_CONFIG_DIRS="/etc/xdg" \
        XDG_DATA_DIRS="${XDG_DATA_DIRS:-/usr/local/share:/usr/share}" \
        XDG_RUNTIME_DIR="$runtime" \
        XDG_SESSION_TYPE="wayland" \
        QT_QPA_PLATFORM="wayland" \
        QSG_RENDER_LOOP="${QSG_RENDER_LOOP:-basic}" \
        GTK_USE_PORTAL="0" \
        "$dbus_binary" -- \
        "$kwin_binary" \
        --virtual \
        --width "$width" \
        --height "$height" \
        --scale "$current_scale" \
        --output-count "$outputs" \
        --no-lockscreen \
        --no-global-shortcuts \
        --exit-with-session "$launcher" &
    active_pid=$!
    # setsid makes the session leader its own process-group leader.
    session_pgid=$active_pid

    wait "$active_pid"
    status=$?
    active_pid=""

    if [[ "$current_scale" != "1" ]]; then
        # The guard records its final status before the command runs or the
        # launcher exits. A missing or unfinished record with KWin already
        # gone means setup never completed validly; cleanup reaps the group.
        guard_status="$(cat "$guard_status_file" 2>/dev/null || true)"
        if [[ "$guard_status" != "0" ]]; then
            printf 'run-kwin-virtual: scale %s guard failed (status %s)\n' \
                "$current_scale" "${guard_status:-unavailable}" >&2
            ((status == 0)) && status=3
        fi
    fi

    # No test command may survive its private KWin session, including one
    # orphaned by an early KWin exit.
    stop_owned_session

    if ((status != 0)); then
        printf 'run-kwin-virtual: scale %s failed with exit %s\n' \
            "$current_scale" "$status" >&2
    fi
    return "$status"
}

if $matrix; then
    scales=("1" "1.25" "1.5" "2")
else
    scales=("$scale")
fi

result=0
for current_scale in "${scales[@]}"; do
    run_one "$current_scale"
    status=$?
    if ((status != 0)) && ((result == 0)); then
        result=$status
    fi
done

exit "$result"
